# Snapshot report for `test/prefer-await.mjs`

The actual snapshot is saved in `prefer-await.mjs.snap`.

Generated by [AVA](https://avajs.dev).

## Invalid #1
      1 | promise.then(() => {})

> Error 1/1

    `␊
    > 1 | promise.then(() => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | await promise;␊
      2 | {}␊
    `

## Invalid #2
      1 | promise.then(foo)

> Error 1/1

    `␊
    > 1 | promise.then(foo)␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | foo(await promise)␊
    `

## Invalid #3
      1 | promise.then(null, () => {})

> Error 1/1

    `␊
    > 1 | promise.then(null, () => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    `

## Invalid #4
      1 | promise.then(null, foo)

> Error 1/1

    `␊
    > 1 | promise.then(null, foo)␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    `

## Invalid #5
      1 | promise.catch(() => {})

> Error 1/1

    `␊
    > 1 | promise.catch(() => {})␊
        |         ^^^^^ Do not use \`Promise#catch(…)\`.␊
    `

## Invalid #6
      1 | promise.catch(foo)

> Error 1/1

    `␊
    > 1 | promise.catch(foo)␊
        |         ^^^^^ Do not use \`Promise#catch(…)\`.␊
    `

## Invalid #7
      1 | promise.finally(() => {})

> Error 1/1

    `␊
    > 1 | promise.finally(() => {})␊
        |         ^^^^^^^ Do not use \`Promise#finally(…)\`.␊
    `

## Invalid #8
      1 | promise.finally(foo)

> Error 1/1

    `␊
    > 1 | promise.finally(foo)␊
        |         ^^^^^^^ Do not use \`Promise#finally(…)\`.␊
    `

## Invalid #9
      1 | promise.then(foo)

> Error 1/1

    `␊
    > 1 | promise.then(foo)␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | foo(await promise)␊
    `

## Invalid #10
      1 | promise.then(foo);

> Error 1/1

    `␊
    > 1 | promise.then(foo);␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | foo(await promise);␊
    `

## Invalid #11
      1 | promise.then(foo.bar);

> Error 1/1

    `␊
    > 1 | promise.then(foo.bar);␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | foo.bar(await promise);␊
    `

## Invalid #12
      1 | promise.then( (( foo )) )

> Error 1/1

    `␊
    > 1 | promise.then( (( foo )) )␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | (( foo ))(await promise)␊
    `

## Invalid #13
      1 | promise.then(new Foo)

> Error 1/1

    `␊
    > 1 | promise.then(new Foo)␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | (new Foo)(await promise)␊
    `

## Invalid #14
      1 | promise.then(foo ?? bar)

> Error 1/1

    `␊
    > 1 | promise.then(foo ?? bar)␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | (foo ?? bar)(await promise)␊
    `

## Invalid #15
      1 | const foo = []
      2 | promise.then([foo][0])

> Error 1/1

    `␊
      1 | const foo = []␊
    > 2 | promise.then([foo][0])␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | const foo = []␊
      2 | ;[foo][0](await promise)␊
    `

## Invalid #16
      1 | promise.then(() => {})

> Error 1/1

    `␊
    > 1 | promise.then(() => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | await promise;␊
      2 | {}␊
    `

## Invalid #17
      1 | promise.then(() => ({}))

> Error 1/1

    `␊
    > 1 | promise.then(() => ({}))␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | await promise;␊
      2 | ({})␊
    `

## Invalid #18
      1 | promise.then(() => {
      2 | 	return []
      3 | })

> Error 1/1

    `␊
    > 1 | promise.then(() => {␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
      2 | 	return []␊
      3 | })␊
    `

## Invalid #19
      1 | promise.then(() => {
      2 | 	function a() {
      3 | 		return []
      4 | 	}
      5 | })

> Error 1/1

    `␊
    > 1 | promise.then(() => {␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
      2 | 	function a() {␊
      3 | 		return []␊
      4 | 	}␊
      5 | })␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | await promise;␊
      2 | {␊
      3 | 	function a() {␊
      4 | 		return []␊
      5 | 	}␊
      6 | }␊
    `

## Invalid #20
      1 | promise.then((a) => {})

> Error 1/1

    `␊
    > 1 | promise.then((a) => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | let a = await promise;␊
      2 | {}␊
    `

## Invalid #21
      1 | promise.then(({a}) => {})

> Error 1/1

    `␊
    > 1 | promise.then(({a}) => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | let {a} = await promise;␊
      2 | {}␊
    `

## Invalid #22
      1 | promise.then(([]) => {})

> Error 1/1

    `␊
    > 1 | promise.then(([]) => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | await promise;␊
      2 | {}␊
    `

## Invalid #23
      1 | promise.then(({}) => {})

> Error 1/1

    `␊
    > 1 | promise.then(({}) => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | await promise;␊
      2 | {}␊
    `

## Invalid #24
      1 | promise.then(({a}) => {
      2 | 	const b = 1;
      3 | })

> Error 1/1

    `␊
    > 1 | promise.then(({a}) => {␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
      2 | 	const b = 1;␊
      3 | })␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | let {a} = await promise;␊
      2 | {␊
      3 | 	const b = 1;␊
      4 | }␊
    `

## Invalid #25
      1 | const a = 1, b = 2;
      2 | promise.then(({a}) => {
      3 | 	const b = 1;
      4 | })

> Error 1/1

    `␊
      1 | const a = 1, b = 2;␊
    > 2 | promise.then(({a}) => {␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
      3 | 	const b = 1;␊
      4 | })␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | const a = 1, b = 2;␊
      2 | {␊
      3 | let {a} = await promise;␊
      4 | {␊
      5 | 	const b = 1;␊
      6 | }␊
      7 | }␊
    `

## Invalid #26
      1 | (( promise.then(() => {}) ))

> Error 1/1

    `␊
    > 1 | (( promise.then(() => {}) ))␊
        |            ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 |  await promise;␊
      2 | {} ␊
    `

## Invalid #27
      1 | promise.then(async () => {})

> Error 1/1

    `␊
    > 1 | promise.then(async () => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    `

## Invalid #28
      1 | promise.then(function * () {})

> Error 1/1

    `␊
    > 1 | promise.then(function * () {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    `

## Invalid #29
      1 | promise.then(async function * () {})

> Error 1/1

    `␊
    > 1 | promise.then(async function * () {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    `

## Invalid #30
      1 | promise.then((...foo) => {})

> Error 1/1

    `␊
    > 1 | promise.then((...foo) => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    `

## Invalid #31
      1 | promise.then((a, extraParameter) => {})

> Error 1/1

    `␊
    > 1 | promise.then((a, extraParameter) => {})␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
    `

## Invalid #32
      1 | function a () {
      2 | 	promise.then(call);
      3 | }

> Error 1/1

    `␊
      1 | function a () {␊
    > 2 | 	promise.then(call);␊
        | 	        ^^^^ Do not use \`Promise#then(…)\`.␊
      3 | }␊
    `

## Invalid #33
      1 | async function a() {
      2 | 	promise.then(call);
      3 | }

> Error 1/1

    `␊
      1 | async function a() {␊
    > 2 | 	promise.then(call);␊
        | 	        ^^^^ Do not use \`Promise#then(…)\`.␊
      3 | }␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | async function a() {␊
      2 | 	call(await promise);␊
      3 | }␊
    `

## Invalid #34
      1 | async function * a() {
      2 | 	promise.then(call);
      3 | }

> Error 1/1

    `␊
      1 | async function * a() {␊
    > 2 | 	promise.then(call);␊
        | 	        ^^^^ Do not use \`Promise#then(…)\`.␊
      3 | }␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | async function * a() {␊
      2 | 	call(await promise);␊
      3 | }␊
    `

## Invalid #35
      1 | const object = {
      2 | 	a() {
      3 | 		promise.then(call);
      4 | 	}
      5 | }

> Error 1/1

    `␊
      1 | const object = {␊
      2 | 	a() {␊
    > 3 | 		promise.then(call);␊
        | 		        ^^^^ Do not use \`Promise#then(…)\`.␊
      4 | 	}␊
      5 | }␊
    `

## Invalid #36
      1 | const object = {
      2 | 	async a() {
      3 | 		promise.then(call);
      4 | 	}
      5 | }

> Error 1/1

    `␊
      1 | const object = {␊
      2 | 	async a() {␊
    > 3 | 		promise.then(call);␊
        | 		        ^^^^ Do not use \`Promise#then(…)\`.␊
      4 | 	}␊
      5 | }␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | const object = {␊
      2 | 	async a() {␊
      3 | 		call(await promise);␊
      4 | 	}␊
      5 | }␊
    `

## Invalid #37
      1 | const object = {
      2 | 	async * a() {
      3 | 		promise.then(call);
      4 | 	}
      5 | }

> Error 1/1

    `␊
      1 | const object = {␊
      2 | 	async * a() {␊
    > 3 | 		promise.then(call);␊
        | 		        ^^^^ Do not use \`Promise#then(…)\`.␊
      4 | 	}␊
      5 | }␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | const object = {␊
      2 | 	async * a() {␊
      3 | 		call(await promise);␊
      4 | 	}␊
      5 | }␊
    `

## Invalid #38
      1 | class A {
      2 | 	a() {
      3 | 		promise.then(call);
      4 | 	}
      5 | }

> Error 1/1

    `␊
      1 | class A {␊
      2 | 	a() {␊
    > 3 | 		promise.then(call);␊
        | 		        ^^^^ Do not use \`Promise#then(…)\`.␊
      4 | 	}␊
      5 | }␊
    `

## Invalid #39
      1 | class A {
      2 | 	async a() {
      3 | 		promise.then(call);
      4 | 	}
      5 | }

> Error 1/1

    `␊
      1 | class A {␊
      2 | 	async a() {␊
    > 3 | 		promise.then(call);␊
        | 		        ^^^^ Do not use \`Promise#then(…)\`.␊
      4 | 	}␊
      5 | }␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | class A {␊
      2 | 	async a() {␊
      3 | 		call(await promise);␊
      4 | 	}␊
      5 | }␊
    `

## Invalid #40
      1 | class A {
      2 | 	async * a() {
      3 | 		promise.then(call);
      4 | 	}
      5 | }

> Error 1/1

    `␊
      1 | class A {␊
      2 | 	async * a() {␊
    > 3 | 		promise.then(call);␊
        | 		        ^^^^ Do not use \`Promise#then(…)\`.␊
      4 | 	}␊
      5 | }␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | class A {␊
      2 | 	async * a() {␊
      3 | 		call(await promise);␊
      4 | 	}␊
      5 | }␊
    `

## Invalid #41
      1 | promise.then(call1)
      2 | 	.then(call2)
      3 | 	.then(call3);

> Error 1/3

    `␊
    > 1 | promise.then(call1)␊
        |         ^^^^ Do not use \`Promise#then(…)\`.␊
      2 | 	.then(call2)␊
      3 | 	.then(call3);␊
    `

> Error 2/3

    `␊
      1 | promise.then(call1)␊
    > 2 | 	.then(call2)␊
        | 	 ^^^^ Do not use \`Promise#then(…)\`.␊
      3 | 	.then(call3);␊
    `

> Error 3/3

    `␊
      1 | promise.then(call1)␊
      2 | 	.then(call2)␊
    > 3 | 	.then(call3);␊
        | 	 ^^^^ Do not use \`Promise#then(…)\`.␊
    ␊
    --------------------------------------------------------------------------------␊
    Suggestion 1/1: Use \`await\` expression.␊
      1 | call3(await promise.then(call1)␊
      2 | 	.then(call2));␊
    `

## Invalid #42
      1 | try {
      2 | 	promise.then(call);
      3 | } catch {}

> Error 1/1

    `␊
      1 | try {␊
    > 2 | 	promise.then(call);␊
        | 	        ^^^^ Do not use \`Promise#then(…)\`.␊
      3 | } catch {}␊
    `

## Invalid #43
      1 | function foo() {
      2 | 	return promise.then(call1)
      3 | }

> Error 1/1

    `␊
      1 | function foo() {␊
    > 2 | 	return promise.then(call1)␊
        | 	               ^^^^ Do not use \`Promise#then(…)\`.␊
      3 | }␊
    `
