# Snapshot report for `test/throw-new-error.js`

The actual snapshot is saved in `throw-new-error.js.snap`.

Generated by [AVA](https://avajs.dev).

## invalid(1): throw Error()

> Input

    `␊
      1 | throw Error()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw Error()␊
        |       ^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new Error()␊
    `

## invalid(2): throw (Error)()

> Input

    `␊
      1 | throw (Error)()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw (Error)()␊
        |       ^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new (Error)()␊
    `

## invalid(3): throw lib.Error()

> Input

    `␊
      1 | throw lib.Error()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw lib.Error()␊
        |       ^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new lib.Error()␊
    `

## invalid(4): throw lib.mod.Error()

> Input

    `␊
      1 | throw lib.mod.Error()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw lib.mod.Error()␊
        |       ^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new lib.mod.Error()␊
    `

## invalid(5): throw lib[mod].Error()

> Input

    `␊
      1 | throw lib[mod].Error()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw lib[mod].Error()␊
        |       ^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new lib[mod].Error()␊
    `

## invalid(6): throw (lib.mod).Error()

> Input

    `␊
      1 | throw (lib.mod).Error()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw (lib.mod).Error()␊
        |       ^^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new (lib.mod).Error()␊
    `

## invalid(7): throw Error('foo')

> Input

    `␊
      1 | throw Error('foo')␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw Error('foo')␊
        |       ^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new Error('foo')␊
    `

## invalid(8): throw CustomError('foo')

> Input

    `␊
      1 | throw CustomError('foo')␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw CustomError('foo')␊
        |       ^^^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new CustomError('foo')␊
    `

## invalid(9): throw FooBarBazError('foo')

> Input

    `␊
      1 | throw FooBarBazError('foo')␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw FooBarBazError('foo')␊
        |       ^^^^^^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new FooBarBazError('foo')␊
    `

## invalid(10): throw ABCError('foo')

> Input

    `␊
      1 | throw ABCError('foo')␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw ABCError('foo')␊
        |       ^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new ABCError('foo')␊
    `

## invalid(11): throw Abc3Error('foo')

> Input

    `␊
      1 | throw Abc3Error('foo')␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw Abc3Error('foo')␊
        |       ^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new Abc3Error('foo')␊
    `

## invalid(12): throw TypeError()

> Input

    `␊
      1 | throw TypeError()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw TypeError()␊
        |       ^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new TypeError()␊
    `

## invalid(13): throw EvalError()

> Input

    `␊
      1 | throw EvalError()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw EvalError()␊
        |       ^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new EvalError()␊
    `

## invalid(14): throw RangeError()

> Input

    `␊
      1 | throw RangeError()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw RangeError()␊
        |       ^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new RangeError()␊
    `

## invalid(15): throw ReferenceError()

> Input

    `␊
      1 | throw ReferenceError()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw ReferenceError()␊
        |       ^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new ReferenceError()␊
    `

## invalid(16): throw SyntaxError()

> Input

    `␊
      1 | throw SyntaxError()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw SyntaxError()␊
        |       ^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new SyntaxError()␊
    `

## invalid(17): throw URIError()

> Input

    `␊
      1 | throw URIError()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw URIError()␊
        |       ^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new URIError()␊
    `

## invalid(18): throw (( URIError() ))

> Input

    `␊
      1 | throw (( URIError() ))␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw (( URIError() ))␊
        |          ^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw (( new URIError() ))␊
    `

## invalid(19): throw (( URIError ))()

> Input

    `␊
      1 | throw (( URIError ))()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw (( URIError ))()␊
        |       ^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new (( URIError ))()␊
    `

## invalid(20): throw getGlobalThis().Error()

> Input

    `␊
      1 | throw getGlobalThis().Error()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw getGlobalThis().Error()␊
        |       ^^^^^^^^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new (getGlobalThis().Error)()␊
    `

## invalid(21): throw utils.getGlobalThis().Error()

> Input

    `␊
      1 | throw utils.getGlobalThis().Error()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw utils.getGlobalThis().Error()␊
        |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new (utils.getGlobalThis().Error)()␊
    `

## invalid(22): throw (( getGlobalThis().Error ))()

> Input

    `␊
      1 | throw (( getGlobalThis().Error ))()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw (( getGlobalThis().Error ))()␊
        |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw new (( getGlobalThis().Error ))()␊
    `

## invalid(23): const error = Error()

> Input

    `␊
      1 | const error = Error()␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | const error = Error()␊
        |               ^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | const error = new Error()␊
    `

## invalid(24): throw Object.assign(Error(), {foo})

> Input

    `␊
      1 | throw Object.assign(Error(), {foo})␊
    `

> Error 1/1

    `␊
    Message:␊
    > 1 | throw Object.assign(Error(), {foo})␊
        |                     ^^^^^^^ Use \`new\` when creating an error.␊
    ␊
    Output:␊
      1 | throw Object.assign(new Error(), {foo})␊
    `

## invalid(25): new Promise((resolve, reject) => { reject(Error('message')); });

> Input

    `␊
      1 | new Promise((resolve, reject) => {␊
      2 | 	reject(Error('message'));␊
      3 | });␊
    `

> Error 1/1

    `␊
    Message:␊
      1 | new Promise((resolve, reject) => {␊
    > 2 | 	reject(Error('message'));␊
        | 	       ^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
      3 | });␊
    ␊
    Output:␊
      1 | new Promise((resolve, reject) => {␊
      2 | 	reject(new Error('message'));␊
      3 | });␊
    `

## invalid(26): function foo() { return[globalThis][0].Error('message'); }

> Input

    `␊
      1 | function foo() {␊
      2 | 	return[globalThis][0].Error('message');␊
      3 | }␊
    `

> Error 1/1

    `␊
    Message:␊
      1 | function foo() {␊
    > 2 | 	return[globalThis][0].Error('message');␊
        | 	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use \`new\` when creating an error.␊
      3 | }␊
    ␊
    Output:␊
      1 | function foo() {␊
      2 | 	return new [globalThis][0].Error('message');␊
      3 | }␊
    `
